---
title: Joseph Lee | A designer living in Seattle
url: http://josephrlee.com
timezone: Pacific Time (US & Canada)
permalink: pretty
markdown: kramdown
description: I’m a product designer, living in Seattle, who is passionate about telling
  stories and growing brands through design that is deliberate, functional, and elegant.
footer: Thanks for checking out my work. If you're interested in learning more, I'd
  love to <a href="mailto:josephrlee@gmail.com" title="Say Hello">hear from you</a>.
  You can also find me on <a href="http://www.linkedin.com/in/josephrlee" title="My
  profile on LinkedIn">LinkedIn</a>.
colophon: This site was built using <a href="http://siteleaf.com">SiteLeaf</a>, <a
  href="https://atom.io/">Atom</a>, <a href="https://www.iterm2.com/">iTerm</a>, <a
  href="http://sass-lang.com/">Sass</a>, <a href="https://github.com/josephrlee">Github</a>,
  Photoshop, and <a href="http://typekit.com">Typekit</a>.
collections:
  uploads:
    title: Uploads
    output: true
  home:
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    permalink: "/posts/:title/"
